### ISSUE TITLE
Documentation for 'two-simulators demo'

### ISSUE THREAD

**Issue by BattulaSwathi** [FNCS/FNCS-Tutorial#6]
a. It is not clear why simB(or simulator B)  requires a higher value for time_desired(time_desired =2 for simB whereas it is '1' for simA), or the circumstances this situation arises. What does it represent when time_granted < time_desired, does it mean the simB is kept on hold?
 The time_step for both simulators simA and simB are the same, in case it is different what are the changes to be made for simA/simB.

b. How are the methods/routines 'fncs::publish' and 'fncs::route' different? While using fncs::route(endPointX, endPointY,..,..), what exactly the endpoints X and Y represent, is it physical address of any node?

c. Documentation available for .zpl configuration is limited.
It is said that simB is not subscribed to any simulator whereas simA is subscribed to listen to simB. The same is not clearly interpreted from the simB.zpl ad simA.zpl files because

for simB.zpl, it says
values
        foo = simA/object.attribute

where as for simA.zpl,
values
        key
        topic = simB/object.attribute
        end = simA/endpointX@endpointY/key

It is hard to know which represents the subscription.

d. In the demo, there is no control over who receives or subscribes to receive messages from published values from a particular simulator. Is it possible to enable such a control in the available version of FNCS?

**Comment by jeffdaily** [comment]
## a)

simB having a time_desired of +2 is trying to demonstrate that the simulators can step at different intervals.  Though both simA and simB support a time delta of "1s" -- one second -- (see the *.zpl files), they can request any multiple of that time delta when advancing.  For example, GridLAB-D can step at minimum one second, but if it is in a steady state it might advance 5 or more seconds.  This is allowed.  If you had, for example, more than one GridLAB-D instance, they could both request different advances.  That is what this simA/simB difference is demonstrating.  If you execute 'run.sh' and look at the log output from simB, you'll see 
```
SimB: Working. Time is 0
SimB: time_request current=0 desired=2 granted=1
SimB: Working. Time is 1
```
You'll see that simB did request to go to 2, but was granted a smaller value because simA had sent a message at timestep T=1, and since simB subscribed to that particular value update it needed to be granted the nearest timestep that could handle the incoming data.  simB is not kept on hold, but is rather granted an earlier time.

On the other hand, if simA had not published a value, simB would have been put on hold until time T=2 had been reached.  At that point, simB would have been granted T=2.

## b)

fncs:publish() is for updating a key/value pair.  fncs::route() is similar, though it represents a point to point message across a communications network.

When you call publish(), the 'key' is prefixed with the name of the simulator before sending out to subscribers.  For example for "simA", publish("key", "value") turns into "simA/key" as the transmitted key.  route("endpointX", "endpointY", "key", "value") turns into "simA/endpointX@endpointY/key" as the transmitted key.  Subscribers to route-type messages use this embedded endpoint information to utilize routing tables in a simulated network.

## c)

We have our ZPL documentation [here](https://github.com/FNCS/fncs/wiki/Configuration-Files-for-Simulators#zpl-formatted-configuration-file).  The fields default, type, and list are optional and can be omitted.  In fact, they are omitted from the sample ZPL files in this demo.  

The lookup key and topic is always required.  We introduced (though it wasn't documented, it seems) a shorthand notation for this as shown in the simB.zpl file
```
values
    foo = simA/object.attribute
```
Whereas in the simA.zpl, it uses the original notation for one value, and inline for another.
```
values
    key
        topic = simB/object.attribute
    end = simA/endpointX@endpointY/key
```
The tracer.zpl file shows an even shorter notation, where it is assumed that the lookup key will be the same as the topic name.
```
    simA/endpointX@endpointY/key
    simA/object.attribute
    simB/object.attribute
```
## d)

In this demo, simA publishes "object.attribute" as well as "this.will.be.dropped".  The latter key, because simB does not subscribe (nor the tracer, if you use that part of the demo), it is silently dropped.  A simulator that publishes a topic will deliver its value to all subscribers of that topic.  There is no way to send a topic to a subset of subscribers, unless you set up a separate topic that only that particular subset of simulators was subscribed to.

**Comment by BattulaSwathi** [comment]
Thanks a lot for your reply. 
I still have concerns over question c)
It is said that simB is not subscribed to any simulator whereas simA is subscribed to listen to simB.
Doesn't the following code
values
    foo = simA/object.attribute
represent simB subscribing to simA?
